name: Build

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cross-toolchain
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: 'lovell/aarch64-linux-musl-crosstools'
          path: aa
      - name: Setup cross toolchain
        # Alpine 3.15 ships with libstc++.28 so we must build with gcc 10 until 3.16 is shipped
        run: |
          ls -a && ls -a aa && cp -r aa/aarch64-linux-musl-cross aarch64-linux-musl-cross && ls && ls aarch64-linux-musl-cross
