name: Build

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup cross toolchain
        # Alpine 3.15 ships with libstc++.28 so we must build with gcc 10 until 3.16 is shipped
        run: |
          curl -O https://more.musl.cc/10/x86_64-linux-musl/aarch64-linux-musl-cross.tgz
